# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: 主页
    url: /
  archives:
    text: 归档
    url: /archives
  tags:
    text: 标签
    url: /tags
  th-list:
    text: 分类
    url: /categories
  bookmark:
    text: 读书
    url: /books
  film:
    text: 电影
    url: /movies
  headphones:
    text: 音乐
    url: /musics
  code:
    text: 作品
    url: /works
  user-secret:
    text: 关于
    url: /about

# github:
#   url: https://github.com/zhouie
#   target: _blank
# weibo:
#   url: http://weibo.com/5736541528/
#   target: _blank


# 你的头像url /assets/images/avatar.jpg
avatar: https://i.loli.net/2019/02/22/5c6f8812ce1c0.jpg
# avatar link
avatar_link: /
# 头像背景图
brand: https://i.loli.net/2019/02/22/5c6f885a1f9fa.jpg
# favicon
favicon: /assets/images/favicon.ico

# email
email: nanzhouie@gmail.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#3F51B5'

# 页面标题
tags_title: 标签
archives_title: 归档
categories_title: 分类

# 文章截断
excerpt_render: false
excerpt_length: 180
excerpt_link: 阅读全文...
mathjax: false
archive_yearly: true

# 是否显示文章最后更新时间
show_last_updated: true

# 是否开启分享
share: true

# 是否开启打赏，关闭 reward: false
reward:
  title: 赠人玫瑰，手有余香
  wechat: https://i.loli.net/2019/02/22/5c6f8f5534b72.jpg     #微信，关闭设为 false
  alipay: https://i.loli.net/2019/02/22/5c6f8f754a6de.jpg     #支付宝，关闭设为 false

# 是否开启搜索
search: true

# 是否大屏幕下文章页隐藏导航
hideMenu: true

# 是否开启toc
# toc: false
toc:
  list_number: true  # 是否显示数字排序

# 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
# postMessage: 这里可以写作者留言，标签和 hexo 中所有变量及辅助函数等均可调用，示例：<a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- page.permalink.replace(/index\.html$/, '') %></a>

# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz_id: 1273664769

# 百度统计，如要开启，改为你的 key ID,负责设为false
baidu_tongji: 691056d9723d4c6dc862bc15de1dc5d4

#百度自动推送功能
baidu_push: true

# 腾讯分析，如要开启，输入站点id
tajs: 65795960
        
# google
google_analytics: UA-117762077-1
google_site_verification: KZ_uFAkIzJs1qHL3SkF_RWRekw1-1d4uoyWOfOFAogo

# less
less:
  compress: true
  paths:
    - source/css/style.less


# 以下评论插件开启一个即可
# 是否开启 disqus
disqus_shortname: false

# 是否开启友言评论, 填写友言用户id
uyan_uid: false

# 是否使用 gitment，https://github.com/imsun/gitment
gitment: false

# gitment:
#  owner: zhouie
#  repo: zhouie.github.io
#  client_id: fd11fc3e8a0403e142bd
#  client_secret: f556ee9f983c7c52a003bfd101c5e3e4c03d8303


# Valine Comment system. https://valine.js.org
valine:
  enable: true # 如果你想使用valine，请将值设置为 true
  appId:  76LtLdyVhce7hiGaqN8kTlgc-gzGzoHsz # your leancloud appId
  appKey: wLgyxnvOp3T5cdL7xO45AC1j # your leancloud appKey
  notify: true # Mail notify
  verify: true # Verify code
  avatar: 'retro'  # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide Link：https://valine.js.org/avatar/
  placeholder: '(ヾﾉ≧∀≦)o来啊，快活啊!' # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 10 # comment list page size

# 是否开启Hyper Comments，填写id则启用，false则禁用。http://hypercomments.com
# Hyper Comments support. Write your id here, or false to disable
hyper_id: false


# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: false

# 版权起始年份
since_year: 2017

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: 学到一句很好的话：“爱的心意大家都是有的，只是爱的能力各有不同，不要因此而否定了爱的存在。”<br>欢迎关注我的微信公众号：<b>北岛向南</b>(ID:nanzhouie)。

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: 站点总访客数：
  site_pv: 站点总访问量：

reading_time: 
  wpm: 180 #每分钟阅读字数
  display: min. #显示文本标识

# 动态定义title
title_change: false
  #normal: (つェ⊂)咦!又好了!
  #leave: 死鬼去哪里了！

# 设置为 true 发布后将使用 unpkg cdn 最新的主题样式
# 如果想让你的自定义样式生效，把此项设为 false
cdn: false

# 设置为 true 将使用 lightbox render 图片
lightbox: true

# icp备案号  ICP_license: 京ICP备1234556号-1
ICP_license: false

# 公安安备号 beian_gov : 43030202001139
beian_gov : 43030202001139
